
/*
 * ENGINE ACTIONS
 */

export const LOAD_ASSETS_PENDING = 'LOAD_ASSETS_PENDING'
export const LOAD_ASSETS_SUCCESS = 'LOAD_ASSETS_SUCCESS'
export const LOAD_ASSETS_ERROR = 'LOAD_ASSETS_ERROR'

export const SETUP_AUDIO_PENDING = 'SETUP_AUDIO_PENDING'
export const SETUP_AUDIO_SUCCESS = 'SETUP_AUDIO_SUCCESS'
export const SETUP_AUDIO_ERROR = 'SETUP_AUDIO_ERROR'

export const PLAY_SOUND = 'PLAY_SOUND'
export const STOP_SOUND = 'STOP_SOUND'
export const STOP_ALL_SOUND = 'STOP_ALL_SOUND'


/*
 * GAME ACTIONS
 */

export const CHANGE_CHIMSER_STATE = 'CHANGE_CHIMSER_STATE'
